name: CI

permissions: {}

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: zemd/js/.github/workflows/shared-ci.yml@29e4b9216068b510a4d1200819ddd3f4383871ed # v4
    permissions:
      contents: read
    with:
      os-matrix: '["ubuntu-latest"]'
      dependency-review-severity: high
