name: Scorecard

permissions: {}

on:
  push:
    branches:
      - main
  branch_protection_rule:
  schedule:
    - cron: "41 5 * * 1"

concurrency:
  group: scorecard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scorecard:
    name: Scorecard
    uses: zemd/js/.github/workflows/shared-scorecard.yml@29e4b9216068b510a4d1200819ddd3f4383871ed # v4
    permissions:
      contents: read # checkout the repository for analysis
      actions: read # inspect workflow runs for dangerous patterns
      security-events: write # upload results to code scanning
      id-token: write # publish results to the OpenSSF API
